baseurl = "https://example.com"
languageCode = "en"
title = "Kanishka Roy"
theme = "charaka-hugo-theme"
copyright = "&copy; <a href=\"https://github.com/natarajmb\">Kanishka Roy</a> 2025"
disqusShortname = ""
relativeURLs = true
preserveTaxonomyNames = true

[services.googleAnalytics]
  ID = ""

[markup.highlight]
  codeFences = true
  guessSyntax = true
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = false
  tabWidth = 4
  noClasses = true
  style = "vulcan" 

[[params.social]]
  url = "about"
  fa_icon = "fas fa-user"
  text = "about me"

[[params.social]]
  url = "principles"
  fa_icon = "fas fa-compass"
  text = "principles"

[[params.social]]
  url = "posts"
  fa_icon = "fas fa-edit"
  text = "posts"

[[params.social]]
  url = "book-reviews"
  fa_icon = "fas fa-book"
  text = "book reviews"